# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.6.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Set up Git in the /build directory
      #   run: cd ./build && git init
      
      # - name: Check the /build directory
      #   run: ls -la ./build

      - name: Write Something
        run: echo 'All done!'

      - name: Deploy to GoDaddy Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          remote-dir: /public_html
          protocol: ftps